name: coffee_cafe_app
description: A new Flutter project.

publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  coolicons: ^1.0.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  flutter_typeahead: ^4.6.2
  uuid: ^4.1.0
  modal_progress_hud_nsn: ^0.3.0
  fluttertoast: ^8.2.2
  firebase_messaging: ^14.6.9
  cloud_firestore: ^4.9.3
  provider: ^6.0.5
  image_picker: ^1.0.4
  file_picker: ^5.3.1
  video_player: ^2.7.2
  firebase_storage: ^11.2.8
  open_file: ^3.3.2
  flutter_pdfview: ^1.3.1
  dio: ^5.3.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  flutter_image_compress: ^2.1.0
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  intl: ^0.19.0
  geolocator: ^11.0.0
  shimmer: ^3.0.0
  page_transition: ^2.1.0
  flutter_card_swiper: ^7.0.0
  flutter_swiper_view: ^1.1.8
  firebase_app_check: ^0.2.1+18
  geocoding: ^3.0.0
  lottie: ^3.1.0
  url_launcher: ^6.2.6
  flutter_pannable_rating_bar: ^2.7.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/pngs/
    - assets/images/jpgs/
    - assets/images/svgs/
    - assets/animations/

  fonts:
    - family: futura
      fonts:
        - asset: assets/fonts/futura/futura.ttf
          weight: 400
        - asset: assets/fonts/futura/futura_medium.ttf
          weight: 600
        - asset: assets/fonts/futura/futura_bold.ttf
          weight: 800
    - family: inter
      fonts:
        - asset: assets/fonts/inter/inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/inter-Regular.ttf
          weight: 500
        - asset: assets/fonts/inter/inter-Medium.ttf
          weight: 700
        - asset: assets/fonts/inter/inter-Bold.ttf
          weight: 800
    - family: Creepster
      fonts:
        - asset: assets/fonts/creepster/Creepster-Regular.ttf
          weight: 500
    - family: Whisper
      fonts:
        - asset: assets/fonts/whisper/Whisper-Regular.ttf